<?php
if (!defined('ABSPATH')) { exit; }

add_action('admin_menu', function () {
    add_menu_page('داشبورد NinjaPet','NinjaPet Pro','manage_options','pettt-dashboard','pettt_admin_dashboard_page','dashicons-pets',3);
    add_submenu_page('pettt-dashboard', 'راهنمای مدیریت محتوا', 'راهنمای مدیریت', 'manage_options', 'pettt-guide', 'pettt_admin_guide_page');
});

function pettt_admin_count($type) { $obj = wp_count_posts($type); return isset($obj->publish) ? (int) $obj->publish : 0; }
function pettt_admin_card($title, $count, $url, $desc) { echo '<a class="pettt-admin-card" href="'.esc_url(admin_url($url)).'"><strong>'.esc_html($count).'</strong><h2>'.esc_html($title).'</h2><p>'.esc_html($desc).'</p></a>'; }

function pettt_admin_dashboard_page() { ?>
<div class="wrap pettt-admin-wrap"><h1>داشبورد مدیریت NinjaPet Pro</h1><p>مدیریت سریع برندها، غذاها، مراکز پت، اکسپلور، تنظیمات، بکاپ و ورود پیامکی.</p><div class="pettt-admin-grid"><?php pettt_admin_card('برندها', pettt_admin_count('pettt_brand'), 'edit.php?post_type=pettt_brand', 'افزودن و ویرایش برندهای ایرانی و خارجی'); ?><?php pettt_admin_card('مدل‌های غذا', pettt_admin_count('pettt_food'), 'edit.php?post_type=pettt_food', 'قیمت حدودی، جدول تغذیه، لینک خرید و آنالیز'); ?><?php pettt_admin_card('ویدیوها', pettt_admin_count('pettt_video'), 'edit.php?post_type=pettt_video', 'آپلود ویدیو یا ثبت کد آپارات'); ?><?php pettt_admin_card('مراکز پت', pettt_admin_count('pettt_service'), 'edit.php?post_type=pettt_service', 'پت‌شاپ، دامپزشکی، آرایشگر و پانسیون'); ?><?php pettt_admin_card('اکسپلور', pettt_admin_count('pettt_explore'), 'edit.php?post_type=pettt_explore', 'تأیید، ویرایش یا حذف پست‌های کاربران'); ?><?php pettt_admin_card('ایمپورت/اکسپورت', 0, 'admin.php?page=ninjapet-data-tools', 'CSV و بکاپ JSON داده‌ها'); ?></div><div class="pettt-admin-panel"><h2>چک‌لیست مدیریت</h2><ol><li>برای هر برند لوگو، کشور، سطح برند، تاریخچه و مدل‌ها را کامل کنید.</li><li>برای غذاها قیمت، لینک خرید، جدول تغذیه و آنالیز را وارد کنید.</li><li>برای مراکز پت، شهر، استان، واتساپ، اینستاگرام، ویدئو و کد مپ را کامل کنید.</li><li>پست‌های اکسپلور کاربران را قبل از انتشار تأیید کنید.</li></ol></div></div><?php }
function pettt_admin_guide_page() { ?><div class="wrap pettt-admin-wrap"><h1>راهنمای مدیریت NinjaPet Pro</h1><div class="pettt-admin-panel"><h2>صفحات پیشنهادی</h2><p>برای پروفایل از قالب «NinjaPet Account Full»، برای ثبت مرکز از «NinjaPet Submit Service» و برای اکسپلور از «NinjaPet Submit Explore» استفاده کنید.</p><h2>ورود پیامکی</h2><p>افزونه رسمی SMS.ir یا دروازه را نصب کنید و در صفحه ورود از شورت‌کد <code>[ninjapet_login]</code> استفاده کنید.</p></div></div><?php }

add_action('admin_enqueue_scripts', function($hook){ if (strpos($hook, 'pettt') === false && strpos($hook, 'ninjapet') === false) return; wp_add_inline_style('wp-admin', '.pettt-admin-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:16px;margin:22px 0}.pettt-admin-card{background:#fff;border:1px solid #e5e7eb;border-radius:16px;padding:20px;text-decoration:none;color:#111827;box-shadow:0 10px 30px rgba(0,0,0,.05)}.pettt-admin-card strong{font-size:34px;color:#5B45F5}.pettt-admin-card h2{margin:8px 0}.pettt-admin-card p{color:#6b7280}.pettt-admin-panel{background:#fff;border-radius:16px;padding:22px;border:1px solid #e5e7eb;max-width:960px}.pettt-admin-panel li{margin-bottom:8px}@media(max-width:900px){.pettt-admin-grid{grid-template-columns:1fr}}'); });

add_filter('manage_pettt_food_posts_columns', function($columns){ $columns['pettt_price'] = 'قیمت حدودی'; $columns['pettt_brand'] = 'برند'; return $columns; });
add_action('manage_pettt_food_posts_custom_column', function($column, $post_id){ if ($column === 'pettt_price') echo esc_html(pettt_meta($post_id, '_pettt_price', '-')); if ($column === 'pettt_brand') echo esc_html(pettt_meta($post_id, '_pettt_brand_id', '-')); }, 10, 2);
add_filter('manage_pettt_service_posts_columns', function($columns){ $columns['pettt_city'] = 'شهر'; $columns['pettt_phone'] = 'تماس'; return $columns; });
add_action('manage_pettt_service_posts_custom_column', function($column, $post_id){ if ($column === 'pettt_city') echo esc_html(pettt_meta($post_id, '_pettt_city', '-')); if ($column === 'pettt_phone') echo esc_html(pettt_meta($post_id, '_pettt_phone', '-')); }, 10, 2);
