<?php
/* Template Name: NinjaPet Account Full */
get_header(); ?>
<section class="pettt-account-hero"><div class="pettt-container"><span class="pettt-kicker">NinjaPet Profile</span><h1>حساب کاربری و پروفایل پت</h1><p>مدیریت پت‌ها، یادآورها، پیشنهاد غذا و پست‌های اکسپلور.</p></div></section>
<section class="pettt-container pettt-account-layout">
<?php if(!is_user_logged_in()): echo do_shortcode('[ninjapet_login]'); else: $user_id=get_current_user_id(); $pets=pettt_account_get_pets($user_id); $reminders=pettt_account_get_reminders($user_id); ?>
<aside class="pettt-account-sidebar"><div class="pettt-account-user"><?php echo get_avatar($user_id,92); ?><h3><?php echo esc_html(wp_get_current_user()->display_name); ?></h3><p><?php echo esc_html(wp_get_current_user()->user_email); ?></p></div><a class="pettt-primary" href="<?php echo esc_url(home_url('/submit-explore')); ?>">ارسال پست اکسپلور</a><a class="pettt-secondary" href="<?php echo esc_url(wp_logout_url(home_url('/'))); ?>">خروج</a></aside>
<div class="pettt-account-main"><div class="pettt-account-card"><h2>افزودن پت جدید</h2><form method="post" class="pettt-account-form"><?php wp_nonce_field('pettt_account_save','pettt_account_nonce'); ?><label>اسم پت<input name="pet_name" required></label><label>جنسیت<select name="pet_gender"><option>نر</option><option>ماده</option></select></label><label>نژاد<input name="pet_breed"></label><label>وزن<input name="pet_weight"></label><label>غذای محبوب<input name="pet_food"></label><label>بیماری یا حساسیت<input name="pet_disease"></label><label>لینک عکس پت<input name="pet_photo"></label><button class="pettt-primary" name="pettt_save_pet" value="1">ذخیره پت</button></form></div>
<div class="pettt-account-card"><h2>پت‌های من</h2><div class="pettt-pet-list"><?php if($pets): foreach($pets as $pet): ?><article class="pettt-pet-item"><?php if(!empty($pet['photo'])) echo '<img src="'.esc_url($pet['photo']).'" alt="'.esc_attr($pet['name']).'">'; ?><div><h3><?php echo esc_html($pet['name']); ?></h3><p><?php echo esc_html(($pet['breed'] ?? '') . ' | ' . ($pet['gender'] ?? '')); ?></p><span>غذای محبوب: <?php echo esc_html($pet['food'] ?? 'ثبت نشده'); ?></span><small>بیماری/حساسیت: <?php echo esc_html($pet['disease'] ?? 'ندارد'); ?></small></div></article><?php endforeach; else: ?><p>هنوز پتی ثبت نکرده‌اید.</p><?php endif; ?></div></div>
<?php if($pets) echo pettt_render_recommendations_for_pet($pets[0]); echo do_shortcode('[ninjapet_my_explore_posts]'); ?>
<div class="pettt-account-card"><h2>تقویم یادآور ایرانی</h2><form method="post" class="pettt-account-form reminder"><?php wp_nonce_field('pettt_account_save','pettt_account_nonce'); ?><label>عنوان<input name="reminder_title" required></label><label>تاریخ ایرانی<input name="reminder_date" required placeholder="۱۴۰۳/۱۰/۰۱"></label><label>ساعت<input name="reminder_time"></label><label>نوع<select name="reminder_type"><option>دامپزشکی</option><option>خرید غذا</option><option>واکسیناسیون</option><option>آرایشگاه</option></select></label><button class="pettt-primary" name="pettt_save_reminder" value="1">افزودن یادآور</button></form><div class="pettt-reminder-list"><?php if($reminders): foreach(array_reverse($reminders) as $item): ?><article><strong><?php echo esc_html($item['title']); ?></strong><span><?php echo esc_html($item['date'].' - '.$item['time']); ?></span><small><?php echo esc_html($item['type']); ?></small></article><?php endforeach; else: ?><p>یادآوری ثبت نشده است.</p><?php endif; ?></div></div></div>
<?php endif; ?></section><?php get_footer(); ?>
