<?php
/* Template Name: NinjaPet Account Full */
get_header();
$edit_index = isset($_GET['pet_edit']) ? absint($_GET['pet_edit']) : null;
?>
<section class="pettt-account-hero"><div class="pettt-container"><span class="pettt-kicker">NinjaPet Profile</span><h1>حساب کاربری و پروفایل پت</h1><p>مدیریت پت‌ها، مشکلات سلامتی، یادآورها، پیشنهاد غذا و پست‌های اکسپلور.</p></div></section>
<section class="pettt-container pettt-account-layout">
<?php if(!is_user_logged_in()): echo do_shortcode('[ninjapet_login]'); else: $user_id=get_current_user_id(); $pets=pettt_account_get_pets($user_id); $reminders=pettt_account_get_reminders($user_id); $edit_pet = ($edit_index !== null && isset($pets[$edit_index])) ? $pets[$edit_index] : null; ?>
<aside class="pettt-account-sidebar"><div class="pettt-account-user"><?php echo get_avatar($user_id,92); ?><h3><?php echo esc_html(wp_get_current_user()->display_name); ?></h3><p><?php echo esc_html(wp_get_current_user()->user_email); ?></p></div><a class="pettt-primary" href="<?php echo esc_url(home_url('/food-advisor')); ?>">پیشنهاد غذا</a><a class="pettt-secondary" href="<?php echo esc_url(home_url('/submit-explore')); ?>">ارسال پست اکسپلور</a><a class="pettt-secondary" href="<?php echo esc_url(wp_logout_url(home_url('/'))); ?>">خروج</a></aside>
<div class="pettt-account-main"><div class="pettt-account-card"><h2><?php echo $edit_pet ? 'ویرایش پت' : 'افزودن پت جدید'; ?></h2><form method="post" class="pettt-account-form"><?php wp_nonce_field('pettt_account_save','pettt_account_nonce'); ?><input type="hidden" name="pet_index" value="<?php echo esc_attr($edit_pet ? $edit_index : ''); ?>"><label>اسم پت<input name="pet_name" required value="<?php echo esc_attr($edit_pet['name'] ?? ''); ?>"></label><label>نوع پت<select name="pet_type"><option <?php selected($edit_pet['type'] ?? '', 'گربه'); ?>>گربه</option><option <?php selected($edit_pet['type'] ?? '', 'سگ'); ?>>سگ</option></select></label><label>جنسیت<select name="pet_gender"><option <?php selected($edit_pet['gender'] ?? '', 'نر'); ?>>نر</option><option <?php selected($edit_pet['gender'] ?? '', 'ماده'); ?>>ماده</option></select></label><label>نژاد<input name="pet_breed" value="<?php echo esc_attr($edit_pet['breed'] ?? ''); ?>"></label><label>سن<input name="pet_age" placeholder="مثلاً ۲ سال" value="<?php echo esc_attr($edit_pet['age'] ?? ''); ?>"></label><label>وزن<input name="pet_weight" value="<?php echo esc_attr($edit_pet['weight'] ?? ''); ?>"></label><label>غذای محبوب<input name="pet_food" value="<?php echo esc_attr($edit_pet['food'] ?? ''); ?>"></label><label>لینک عکس پت<input name="pet_photo" value="<?php echo esc_attr($edit_pet['photo'] ?? ''); ?>"></label><div class="wide"><h3>مشکلات یا نیازهای پت</h3><?php echo ninjapet_pet_problems_checkboxes($edit_pet['problems'] ?? []); ?></div><label class="wide">توضیح بیماری یا حساسیت<input name="pet_disease" value="<?php echo esc_attr($edit_pet['disease'] ?? ''); ?>"></label><button class="pettt-primary" name="pettt_save_pet" value="1">ذخیره پت</button></form></div>
<div class="pettt-account-card"><h2>پت‌های من</h2><div class="pettt-pet-list"><?php if($pets): foreach($pets as $i=>$pet): ?><article class="pettt-pet-item"><?php if(!empty($pet['photo'])) echo '<img src="'.esc_url($pet['photo']).'" alt="'.esc_attr($pet['name']).'">'; ?><div><h3><?php echo esc_html($pet['name']); ?></h3><p><?php echo esc_html(($pet['type'] ?? '') . ' | ' . ($pet['breed'] ?? '') . ' | ' . ($pet['age'] ?? '')); ?></p><span>غذای محبوب: <?php echo esc_html($pet['food'] ?? 'ثبت نشده'); ?></span><small>مشکلات: <?php echo esc_html(!empty($pet['problems']) ? implode('، ', (array)$pet['problems']) : ($pet['disease'] ?? 'ندارد')); ?></small><div class="np-pet-actions"><a href="<?php echo esc_url(add_query_arg('pet_edit',$i)); ?>">ویرایش</a><a class="danger" href="<?php echo esc_url(wp_nonce_url(add_query_arg('pet_delete',$i),'ninjapet_delete_pet')); ?>">حذف</a></div></div></article><?php endforeach; else: ?><p>هنوز پتی ثبت نکرده‌اید.</p><?php endif; ?></div></div>
<?php if($pets) echo pettt_render_recommendations_for_pet($pets[0]); echo do_shortcode('[ninjapet_my_explore_posts]'); ?>
<div class="pettt-account-card"><h2>تقویم یادآور ایرانی</h2><form method="post" class="pettt-account-form reminder"><?php wp_nonce_field('pettt_account_save','pettt_account_nonce'); ?><label>عنوان<input name="reminder_title" required placeholder="نوبت دامپزشکی یا خرید غذا"></label><label>تاریخ ایرانی<input name="reminder_date" required placeholder="۱۴۰۳/۱۰/۰۱"></label><label>ساعت<input name="reminder_time" placeholder="۱۸:۳۰"></label><label>نوع<select name="reminder_type"><option>دامپزشکی</option><option>خرید غذا</option><option>واکسیناسیون</option><option>آرایشگاه</option></select></label><button class="pettt-primary" name="pettt_save_reminder" value="1">افزودن یادآور</button></form><div class="pettt-reminder-list"><?php if($reminders): foreach(array_reverse($reminders) as $item): ?><article><strong><?php echo esc_html($item['title']); ?></strong><span><?php echo esc_html($item['date'].' - '.$item['time']); ?></span><small><?php echo esc_html($item['type']); ?></small></article><?php endforeach; else: ?><p>یادآوری ثبت نشده است.</p><?php endif; ?></div></div></div>
<?php endif; ?></section><?php get_footer(); ?>
