import React, { useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Search, Star, Heart, Bell, Home, PawPrint, Sparkles, User, ChevronLeft, ShieldCheck, Scale, Stethoscope, Camera, ImagePlus, Send, MessageCircle, Settings, Plus, ArrowRight, PlayCircle, FileText, X } from 'lucide-react';
import './styles.css';

const brands = [
  { id: 'royal', name: 'رویال کنین', latin: 'Royal Canin', tier: 'سوپرپرمیوم', short: 'RC', country: 'فرانسه', history: 'رویال کنین از شناخته شده ترین برندهای غذای تخصصی پت است و تمرکز اصلی آن روی فرمول های علمی برای نژاد، سن و مشکل سلامتی حیوانات است.', models: ['Gastrointestinal', 'Renal', 'Sterilised', 'Kitten', 'Urinary'], desc: 'فرمول های تخصصی برای سن، نژاد و مشکلات سلامتی پت.' },
  { id: 'acana', name: 'آکانا', latin: 'Acana', tier: 'پرمیوم', short: 'AC', country: 'کانادا', history: 'آکانا روی ترکیبات طبیعی و پروتئین بالا تمرکز دارد و برای پت های فعال انتخاب محبوبی است.', models: ['Indoor Entrée', 'Wild Prairie', 'Grasslands'], desc: 'غذاهای پروتئینی با ترکیبات طبیعی برای پت های فعال.' },
  { id: 'hills', name: 'هیلز', latin: 'Hills', tier: 'درمانی', short: 'HL', country: 'آمریکا', history: 'هیلز یکی از برندهای مهم در غذاهای دامپزشکی است و برای رژیم های گوارشی، کلیوی و کنترل وزن شناخته می شود.', models: ['Digestive Care', 'Metabolic', 'Kidney Care'], desc: 'رژیم های دامپزشکی برای گوارش، کلیه و کنترل وزن.' },
  { id: 'whiskas', name: 'ویسکاس', latin: 'Whiskas', tier: 'اقتصادی', short: 'WK', country: 'تایلند', history: 'ویسکاس یک برند اقتصادی و در دسترس برای تغذیه روزانه گربه هاست.', models: ['Adult Chicken', 'Tuna', 'Kitten'], desc: 'غذای اقتصادی روزانه برای گربه های بالغ سالم.' }
];

const products = [
  { id: 1, brandId: 'royal', brand: 'رویال کنین', name: 'گاسترواینتستینال', problem: 'گوارشی', price: '۱,۸۵۰,۰۰۰', rating: 4.8, color: '#7c3aed', reason: 'برای استفراغ، اسهال و معده حساس مناسب است.' },
  { id: 2, brandId: 'royal', brand: 'رویال کنین', name: 'رنال', problem: 'کلیوی', price: '۱,۹۲۰,۰۰۰', rating: 4.7, color: '#2563eb', reason: 'برای حمایت از کلیه و رژیم دامپزشکی.' },
  { id: 3, brandId: 'acana', brand: 'آکانا', name: 'ایندور انتری', problem: 'کنترل وزن', price: '۲,۲۰۰,۰۰۰', rating: 4.8, color: '#059669', reason: 'برای گربه های داخل خانه و کم تحرک.' },
  { id: 4, brandId: 'hills', brand: 'هیلز', name: 'دایجستیو کر', problem: 'گوارشی', price: '۱,۷۲۰,۰۰۰', rating: 4.7, color: '#ea580c', reason: 'برای هضم بهتر و روده حساس.' },
  { id: 5, brandId: 'whiskas', brand: 'ویسکاس', name: 'ادالت چیکن', problem: 'اقتصادی', price: '۴۹۰,۰۰۰', rating: 4.1, color: '#db2777', reason: 'گزینه ارزان تر برای مصرف روزانه.' }
];

const problems = ['همه', 'گوارشی', 'کلیوی', 'کنترل وزن', 'عقیم', 'اقتصادی'];
const demoImages = ['https://images.unsplash.com/photo-1552053831-71594a27632d?q=80&w=900&auto=format&fit=crop','https://images.unsplash.com/photo-1574158622682-e40e69881006?q=80&w=900&auto=format&fit=crop','https://images.unsplash.com/photo-1583511655826-05700442b31b?q=80&w=900&auto=format&fit=crop'];
const articles = ['چطور غذای مناسب پت دارای مشکل گوارشی انتخاب کنیم؟','نشانه های حساسیت غذایی در گربه و سگ','برنامه تغذیه بعد از عقیم سازی','راهنمای تغییر غذا بدون آسیب به معده'];
const videos = ['آموزش خواندن جدول تغذیه روی بسته غذا','نکات مراقبت از پت های دارای مشکل کلیوی','انتخاب غذای اقتصادی اما قابل قبول','آموزش وزن کشی و کنترل وزن پت'];

function ProductCard({ product }){return <article className="product-card"><div className="bag" style={{background:product.color}}><PawPrint size={26}/></div><div><small>{product.brand}</small><h3>{product.name}</h3><p>{product.reason}</p><b>{product.price} تومان</b></div><span className="rating"><Star size={14} fill="currentColor"/> {product.rating}</span></article>}
function ProblemTabs({selected,setSelected}){return <section className="chips">{problems.map(p=><button key={p} className={selected===p?'active':''} onClick={()=>setSelected(p)}>{p}</button>)}</section>}

function RegisterScreen({pet,setPet,onDone}){const photo=e=>{const f=e.target.files?.[0]; if(f)setPet({...pet,photo:URL.createObjectURL(f)})};return <main className="content top-content"><section className="register-hero"><h1>ثبت نام در Pettt</h1><p>برای دیدن و ساخت پروفایل، ابتدا اطلاعات پتت را ثبت کن.</p></section><section className="pet-card"><label className="pet-photo"><img src={pet.photo||demoImages[0]} /><input type="file" accept="image/*" onChange={photo}/><span><Camera size={18}/></span></label><div><h2>{pet.name||'پت من'}</h2><p>{pet.breed||'نژاد را وارد کن'}</p></div></section><section className="form-card"><label>اسم پت<input value={pet.name} onChange={e=>setPet({...pet,name:e.target.value})}/></label><label>جنسیت<select value={pet.gender} onChange={e=>setPet({...pet,gender:e.target.value})}><option>نر</option><option>ماده</option></select></label><label>نژاد<input value={pet.breed} onChange={e=>setPet({...pet,breed:e.target.value})}/></label><label>وزن<input value={pet.weight} onChange={e=>setPet({...pet,weight:e.target.value})}/></label><label>بیماری خاص<input value={pet.diseases} onChange={e=>setPet({...pet,diseases:e.target.value})}/></label><label>غذای محبوب<input value={pet.food} onChange={e=>setPet({...pet,food:e.target.value})}/></label><button className="publish" onClick={onDone}>ثبت نام و ورود</button></section></main>}

function HomeScreen({setTab,problem,setProblem,list}){return <><header className="hero"><div className="hero-actions"><button><Heart size={19}/></button><button><Bell size={19}/></button></div><p className="eyebrow">Pettt AI Food Finder</p><h1>غذای مناسب پتتو پیدا کن</h1><p>مرجع فارسی برندها، محصولات، پروفایل پت و اکسپلور.</p><button className="search" onClick={()=>setTab('brands')}><Search size={19}/><span>جستجو در برندها و غذاها...</span></button></header><main className="content"><ProblemTabs selected={problem} setSelected={setProblem}/><section className="section-head"><h2>برندهای محبوب</h2><button onClick={()=>setTab('brands')}>مشاهده همه <ChevronLeft size={15}/></button></section><section className="brand-grid">{brands.map(b=><button className="brand" key={b.id} onClick={()=>setTab('brands')}><div>{b.short}</div><strong>{b.name}</strong><small>{b.tier}</small></button>)}</section><button className="banner" onClick={()=>setTab('recommend')}><div><h2>پیشنهاد هوشمند غذا</h2><p>مشکل پتت رو انتخاب کن تا بهترین گزینه ها نمایش داده شود.</p></div><Sparkles size={42}/></button><section className="products">{list.map(p=><ProductCard key={p.id} product={p}/>)}</section></main></>}

function BrandsScreen(){const [q,setQ]=useState('');const [selected,setSelected]=useState(null);const filtered=brands.filter(b=>b.name.includes(q)||b.latin.toLowerCase().includes(q.toLowerCase())||b.tier.includes(q));if(selected){const ps=products.filter(p=>p.brandId===selected.id);return <main className="content top-content"><button className="back" onClick={()=>setSelected(null)}><ArrowRight size={18}/> برگشت</button><section className="brand-detail"><div className="brand-logo big">{selected.short}</div><h1>{selected.name}</h1><p>{selected.latin} | {selected.country} | {selected.tier}</p><span>{selected.history}</span></section><section className="gallery">{demoImages.map(img=><img key={img} src={img}/>)}</section><section className="section-head"><h2>مدل های برند</h2></section><div className="model-list">{selected.models.map(m=><span key={m}>{m}</span>)}</div><section className="products">{ps.map(p=><ProductCard key={p.id} product={p}/>)}</section></main>}return <main className="content top-content"><section className="page-title"><p>کاتالوگ برندها</p><h1>همه برندهای پت</h1></section><label className="input"><Search size={18}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="جستجو در برندها..."/></label><section className="brand-list">{filtered.map(b=><button className="brand-row" key={b.id} onClick={()=>setSelected(b)}><div className="brand-logo">{b.short}</div><div><h3>{b.name}</h3><p>{b.latin} | {b.tier} | {b.country}</p><span>{b.desc}</span></div><b>{products.filter(p=>p.brandId===b.id).length} غذا</b></button>)}</section></main>}

function RecommendScreen({problem,setProblem,list}){const [mode,setMode]=useState('food');return <main className="content top-content"><section className="recommend-hero"><div><p>AI Recommendation</p><h1>پیشنهادها</h1><span>غذا، مقاله و ویدیوهای آموزشی</span></div><Stethoscope size={42}/></section><section className="segmented"><button className={mode==='food'?'active':''} onClick={()=>setMode('food')}>غذا</button><button className={mode==='articles'?'active':''} onClick={()=>setMode('articles')}>مقالات</button><button className={mode==='videos'?'active':''} onClick={()=>setMode('videos')}>ویدیوها</button></section>{mode==='food'&&<><ProblemTabs selected={problem} setSelected={setProblem}/><section className="products">{list.map(p=><ProductCard key={p.id} product={p}/>)}</section></>}{mode==='articles'&&<section className="learn-list">{articles.map(a=><article key={a}><FileText size={22}/><div><h3>{a}</h3><p>مقاله پیشنهادی بر اساس نیازهای رایج پت ها.</p></div></article>)}</section>}{mode==='videos'&&<section className="learn-list">{videos.map(v=><article key={v}><PlayCircle size={24}/><div><h3>{v}</h3><p>بعدا کد اسکریپت آپارات از پنل مدیریت اینجا وارد می شود.</p></div></article>)}</section>}</main>}

function ExploreScreen({posts,setPosts,pet}){const [compose,setCompose]=useState(false);const [commentPost,setCommentPost]=useState(null);const [draft,setDraft]=useState('');const [img,setImg]=useState('');const pic=e=>{const f=e.target.files?.[0];if(f)setImg(URL.createObjectURL(f))};const publish=()=>{if(!img&&!draft.trim())return;setPosts([{id:Date.now(),owner:'شما و '+pet.name,time:'همین الان',petName:pet.name,breed:pet.breed,food:pet.food,caption:draft||'پست جدید من در Pettt',image:img||pet.photo||demoImages[0],likes:0,comments:[],liked:false},...posts]);setCompose(false);setDraft('');setImg('')};const like=id=>setPosts(posts.map(p=>p.id===id||String(p.id)===String(id)?(p.liked?p:{...p,liked:true,likes:p.likes+1}):p));const addComment=txt=>{if(!txt.trim())return;setPosts(posts.map(p=>p.id===commentPost.id?{...p,comments:[...p.comments,txt]}:p));setCommentPost(null)};return <main className="content top-content"><section className="explore-head"><Search size={20}/><h1>اکسپلور</h1><button className="add-btn" onClick={()=>setCompose(true)}><Plus size={22}/></button></section>{compose&&<section className="new-post modal-card"><div className="modal-title"><h2>پست جدید</h2><button onClick={()=>setCompose(false)}><X size={20}/></button></div><label className="upload-box">{img?<img src={img}/>:<><ImagePlus size={36}/><span>عکس پت را انتخاب کن</span></>}<input type="file" accept="image/*" onChange={pic}/></label><textarea value={draft} onChange={e=>setDraft(e.target.value)} placeholder="متن زیر عکس را بنویس..."/><button className="publish" onClick={publish}><Send size={18}/> انتشار</button></section>}<section className="feed">{posts.map(post=><article className="post-card" key={post.id}><div className="post-meta"><div className="mini-avatar">{post.petName.slice(0,1)}</div><div><b>{post.owner}</b><span>{post.time}</span></div></div><img className="post-photo" src={post.image}/><div className="post-body"><h2>{post.petName} <small>{post.breed}</small></h2><p>{post.caption}</p><div className="food-line">غذای محبوب: <b>{post.food}</b></div><div className="post-actions"><button className={post.liked?'liked':''} onClick={()=>like(post.id)}><Heart size={18} fill={post.liked?'currentColor':'none'}/> {post.likes}</button><button onClick={()=>setCommentPost(post)}><MessageCircle size={18}/> {post.comments.length}</button></div></div></article>)}</section>{commentPost&&<CommentModal post={commentPost} close={()=>setCommentPost(null)} add={addComment}/>}</main>}
function CommentModal({post,close,add}){const [text,setText]=useState('');return <section className="comment-modal"><div className="comment-box"><div className="modal-title"><h2>کامنت های {post.petName}</h2><button onClick={close}><X size={20}/></button></div><div className="comments">{post.comments.length?post.comments.map((c,i)=><p key={i}>{c}</p>):<span>هنوز کامنتی ثبت نشده.</span>}</div><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="کامنت بنویس..."/><button className="publish" onClick={()=>add(text)}>ثبت کامنت</button></div></section>}

function ProfileScreen({pet,setPet}){const photo=e=>{const f=e.target.files?.[0]; if(f)setPet({...pet,photo:URL.createObjectURL(f)})};return <main className="content top-content"><section className="profile-top"><Settings size={20}/><h1>پروفایل من</h1><Bell size={20}/></section><section className="pet-card"><label className="pet-photo"><img src={pet.photo||demoImages[0]}/><input type="file" accept="image/*" onChange={photo}/><span><Camera size={18}/></span></label><div><h2>{pet.name} {pet.gender==='نر'?'♂':'♀'}</h2><p>{pet.breed} | {pet.weight} کیلوگرم</p><div className="tag-row">{pet.diseases.split(',').filter(Boolean).map(x=><span key={x}>{x.trim()}</span>)}</div></div></section><section className="form-card"><label>اسم پت<input value={pet.name} onChange={e=>setPet({...pet,name:e.target.value})}/></label><label>جنسیت<select value={pet.gender} onChange={e=>setPet({...pet,gender:e.target.value})}><option>نر</option><option>ماده</option></select></label><label>نژاد<input value={pet.breed} onChange={e=>setPet({...pet,breed:e.target.value})}/></label><label>وزن<input value={pet.weight} onChange={e=>setPet({...pet,weight:e.target.value})}/></label><label>بیماری خاص<input value={pet.diseases} onChange={e=>setPet({...pet,diseases:e.target.value})}/></label><label>غذای محبوب<input value={pet.food} onChange={e=>setPet({...pet,food:e.target.value})}/></label></section></main>}
function BottomNav({tab,setTab}){const items=[['home',Home,'خانه'],['brands',PawPrint,'برندها'],['recommend',Sparkles,'پیشنهادها'],['explore',Search,'اکسپلور'],['profile',User,'پروفایل']];return <nav className="bottom-nav five">{items.map(([id,Icon,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}><Icon size={21}/><span>{label}</span></button>)}</nav>}

function App(){const [registered,setRegistered]=useState(false);const [tab,setTab]=useState('home');const [problem,setProblem]=useState('همه');const [pet,setPet]=useState({name:'بیلی',gender:'نر',breed:'گلدن رتریور',weight:'۲۵',diseases:'مشکل گوارشی, حساسیت پوستی',food:'Royal Canin Gastrointestinal',photo:demoImages[0]});const [posts,setPosts]=useState([{id:3,owner:'النا و لونا',petName:'لونا',breed:'پامرینین',food:'Royal Canin Pomeranian',caption:'امروز کلی بازی کرد و خوشحال بود.',image:demoImages[1],likes:24,comments:['خیلی خوشگله'],liked:false,time:'۵ دقیقه پیش'},{id:2,owner:'نیلوفر و میو',petName:'میو',breed:'بریتیش شورت هیر',food:'Royal Canin Sterilised',caption:'میو عاشق آفتاب کنار پنجره است.',image:demoImages[2],likes:31,comments:[],liked:false,time:'۱۲ دقیقه پیش'}]);const list=useMemo(()=>problem==='همه'?products:products.filter(p=>p.problem===problem),[problem]);if(!registered)return <div className="app-shell"><RegisterScreen pet={pet} setPet={setPet} onDone={()=>setRegistered(true)}/></div>;return <div className="app-shell">{tab==='home'&&<HomeScreen setTab={setTab} problem={problem} setProblem={setProblem} list={list}/>} {tab==='brands'&&<BrandsScreen/>}{tab==='recommend'&&<RecommendScreen problem={problem} setProblem={setProblem} list={list}/>} {tab==='explore'&&<ExploreScreen posts={posts} setPosts={setPosts} pet={pet}/>} {tab==='profile'&&<ProfileScreen pet={pet} setPet={setPet}/>}<BottomNav tab={tab} setTab={setTab}/></div>}

createRoot(document.getElementById('root')).render(<App/>);
